-- ============================================================================
-- deal_analysis — post-mortem analysis for closed deals
-- One row per closed deal. Generated by daily/deal_analysis.py.
-- Consumed by parser → deal_ui for the UI.
-- ============================================================================

CREATE TABLE IF NOT EXISTS deal_analysis (
  deal_id              UUID PRIMARY KEY REFERENCES deals(id) ON DELETE CASCADE,
  outcome              TEXT NOT NULL,

  full_narrative        TEXT,
  outcome_summary       TEXT,
  deal_timeline         JSONB DEFAULT '[]'::jsonb,
  what_worked           JSONB DEFAULT '[]'::jsonb,
  what_failed           JSONB DEFAULT '[]'::jsonb,
  what_could_have_changed TEXT,
  rep_assessment        TEXT,
  key_people            JSONB DEFAULT '[]'::jsonb,
  products_pitched      JSONB DEFAULT '[]'::jsonb,
  products_missed       JSONB DEFAULT '[]'::jsonb,
  product_assessment    TEXT,

  created_at            TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deal_analysis_outcome ON deal_analysis(outcome);

ALTER TABLE deal_analysis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read" ON deal_analysis FOR SELECT TO anon USING (true);
CREATE POLICY "authenticated_read" ON deal_analysis FOR SELECT TO authenticated USING (true);
CREATE POLICY "service_all" ON deal_analysis FOR ALL TO service_role USING (true);
