ALTER TABLE deals ADD COLUMN IF NOT EXISTS after_demo_date TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS after_demo_followup_date TIMESTAMPTZ;
ALTER TABLE deal_ui ADD COLUMN IF NOT EXISTS after_demo_date TIMESTAMPTZ;
ALTER TABLE deal_ui ADD COLUMN IF NOT EXISTS after_demo_followup_date TIMESTAMPTZ;
